spring:
  application:
    name: pos-system-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/imbasac
    username: imbasac
    password: imbasac
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10000
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      file-size-threshold: 2MB
server:
  port: 8091
  address: 0.0.0.0

  level:
    root: INFO

security:
  token:
    secret: bSZWQDl3ZDVtUW0memhHNEc3ME82ZlYmYms5enVFSmU=
    expiration: 1200
  session:
    ttl: 1800


#headless: true → no intenta abrir UI
#debug-enabled: false → no guarda evidencias ni logs debug
#network-log-enabled: false → no ensucia logs con tráfico HTTP del navegador

#integration:
#  mtc-license:
#    search-url: https://slcp.mtc.gob.pe/
#    headless: true
#    timeout-ms: 30000
#    session-ttl-seconds: 120
#    debug-enabled: false
#    network-log-enabled: false
#    debug-dir: /var/www/html/logs/mtc-debug

integration:
  mtc-license:
    search-url: https://slcp.mtc.gob.pe/
    headless: false
    timeout-ms: 30000
    session-ttl-seconds: 120
    debug-enabled: true
    network-log-enabled: true
    debug-dir: logs/mtc-debug

  guide-remission:
    base-url: "http://localhost/API_SUNAT_GUIAS"
    connect-timeout-seconds: 10
    read-timeout-seconds: 60
    auth:
      guias-client-id: "test-85e5b0ae-255c-4891-a595-0b98c65c9854"
      guias-client-secret: "test-Hty/M6QshYvPgItX2P0+Kw=="
      usu-secundario-produccion-user: "MODDATOS"
      usu-secundario-produccion-password: "MODDATOS"
    company:
      ruc: "10481211641"
      razon-social: "IMPORTACIONES BAEZ S.A.C."
      nombre-comercial: "IMBASAC"
      domicilio-fiscal: "AV. LOS EJEMPLOS 123"
      ubigeo: "150101"
      urbanizacion: "-"
      distrito: "LIMA"
      provincia: "LIMA"
      departamento: "LIMA"
      modo: 1

sale:
  sunat:
    mode: "0"
    url: http://localhost/API_SUNAT/post.php
    username: "MODDATOS"
    password: "MODDATOS"
    business:
      ruc: "20611603739"
      businessName: "IMPORTACIONES EL HUECO 365 DIAS DE 1000 OFERTAS S.A.C"
      tradeName: "IMPORTACIONES EL HUECO"
      taxAddress: "JR. SAN CRISTOBAL 327"
      ubigeo: "180101"
      neighborhood: "CHAUPIMARCA"
      district: "CHAUPIMARCA"
      province: "CERRO DE PASCO"
      department: "PASCO"

common:
  hashedPassword: $2a$12$UJsm7R3LJ0IvFNXuOpxB2OPWBrBp/1kTcivvYXlsji2ZlpA.I./j6

#app:
#  files:
#    products-images-dir: /var/www/altoquik/images/products
#    products-images-base-url: http://localhost:8091

app:
  files:
    products-images-dir: src/main/resources/static/images/products
    products-images-base-url: http://localhost:8091/images/products

    manual-pdfs-dir: ./storage/manual-pdfs
    manual-pdfs-public-path: /files/manual-pdfs